---
############################################################################
# ONTAP Select Params
# -------------------------------------------------------------------
# Passwords 
# - Place these in a separate file and implement encryption if needed
# -------------------------------------------------------------------
deploy_login: admin
# ----------------------------------------------------------------
# Configuration Settings
# - Place these variables in a separate .yml file and reference in 
#   the playbook along with the include_role statement
# ----------------------------------------------------------------

# -------------------------------
# Number of nodes in the cluster
# -------------------------------
node_count: 2

# -------------------------------------------
# Hypervisor Type - ESX | KVM (case sensitve)
# -------------------------------------------
hypervisor: ESX

# ------------------------------------------------------------------------
# true = Authenticate through vCenter | false = Authenticate host directly
#        if esxi host is managed by vCenter then you MUST use vCenter
# ------------------------------------------------------------------------
use_vcenter: true

# -------------------------------------------------
# Monitor a job until "success" or "failure"
# - Host registration jobs will always be monitored
# -------------------------------------------------
monitor_deploy_job: false
monitor_deploy_retries: 60
monitor_deploy_delay: 120
monitor_host_retries: 10
monitor_host_delay: 15
monitor_netcheck_retries: 30
monitor_netcheck_delay: 60

# ----------------------------------------------------------------------
# Network Connectivity Check
# - Set to true to run the network connectivity check
# - Valid modes: quick, extended, cleanup
# - Valid switch types: StandardvSwitch, DistributedvSwitch, OpenvSwitch
# - cluster_nodes referenced so make sure item count = node count !!!
# ----------------------------------------------------------------------
run_net_check: false
net_mode: quick
net_mtu: 9000
net_switch_type: StandardvSwitch

# -----------
# Deploy Info
# -----------
deploy_ip: "10.198.66.199"
deploy_api_url: "https://{{ deploy_ip }}/api/v3"
deploy_login: admin

# ------------
# vCenter Info
# ------------
vcenter_login: administrator@vsphere.local
vcenter_name: vc.vsphere.local

# -----
# Hosts
# -----
esxi_hosts:
  - host_name: uk.....111.uk.dev.net
    host_login: 
  - host_name: uk.....112.uk.dev.net
    host_login: 

kvm_hosts:
  - host_name: 
    host_login: 
  - host_name: 
    host_login: 

# ------------
# Cluster Info
# ------------
cluster_name: "uknase24a"
cluster_ip: "10.198.66.45"
cluster_netmask: "255.255.255.128"
cluster_gateway: "10.198.66.1"
cluster_ontap_image: "9.14.1P2"
cluster_ntp:
  - "10.4.32.5"
cluster_dns_ips:
  - "10.4.32.5"
cluster_dns_domains:
  - "uk.dev.net"

# --------
# Networks
# --------
mgt_network: Management
data_network: Data
internal_network: Internal

# --------
# Instance
# --------
instance_type: small

# --------------------------------------------------
# Node Info
# - cluster_nodes # of items should equal node_count
# --------------------------------------------------
cluster_nodes:
  - node_name: "{{ cluster_name }}-01"
    ipAddress: "10.198.66.46"
    storage_pool: "pool-1"
    capacityTB: 3
    host_name: uk.....111.uk.dev.net
  - node_name: "{{ cluster_name }}-02"
    ipAddress: "10.198.66.50"
    storage_pool: "storage-2"
    capacityTB: 3
    host_name: uk.....112.uk.dev.net

# ------------------------------------------
# Capacity Conversion Values
# Note: 1TB    in Bytes = 1099511627776
#       300GB  in Bytes = 322122547200
#       2% 1TB in Bytes = 21990232555
#
# Formula used to calculate Storage Capacity
# ( capacityTB * TBinBytes - Overhead )
# ------------------------------------------
TBinBytes: 1099511627776
Overhead: 322122547200
TB2Percent: 21990232555