---
- name: Install dependencies on RHEL9
  hosts: localhost
  become: yes
  tasks:
    - name: install dependencies from templates
      import_tasks: templates/install_dependencies.yml

- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - prepare_vmware
  tags: prepare_vmware
  vars_files:
    - group_vars/vault.yml

- name: Deploy ONTAP Select
  hosts: localhost
  vars_files:
    - group_vars/ots_deploy.yml
    - group_vars/vault.yml
  roles:
    - na_ots_deploy
  tags: ONTAP Deploy

- name: Deploy ONTAP Select Cluster
  hosts: localhost
  vars_files:
    - group_vars/ots_cluster.yml
    - group_vars/vault.yml
  roles:
    - na_ots_cluster
  tags: ONTAP Cluster

- name: Configure Custom Roles and web access
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  roles:
    - 01.configure_roles
  tags: configure_roles

- name: Creating local users for cluster management
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  roles:
    - 02.local_users
  tags: user_creation

- name: Creating login banner
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  roles:
    - 03.local_banner
  tags: banner_creation

- name: ssh_timeout
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  roles:
    - 04.ssh_timeout
  tags: ssh_timeout

- name: configure_NDMP
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  roles:
    - 05.configure_ndmp
  tags: configure_ndmp

- name: Diable_HTTP
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/vault.yml
    - group_vars/ots_cluster.yml
  tags: disable_http
  