---
- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - prepare_vmware
  tags: prepare_vmware

- name: Deploy ONTAP Select
  hosts: localhost
  roles:
    - na_ots_deploy
  tags: ONTAP Deploy

- name: Deploy Cluster
  hosts: localhost
  roles:
    - na_ots_cluster
  tags: ONTAP Cluster
