---
- name: Install dependencies on RHEL 9
  hosts: localhost
  become: yes
  tasks:
    - import_tasks: templates/install_dependencies.yml

- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - prepare_vmware
  tags: prepare_vmware

- name: Deploy ONTAP Select
  hosts: localhost
  roles:
    - na_ots_deploy
  tags: ONTAP Deploy

- name: Deploy Cluster
  hosts: localhost
  roles:
    - na_ots_cluster
  tags: ONTAP Cluster

- name: Configure Custom Roles
  hosts: localhost
  roles:
    - configure_roles
  tags: configure_roles