# # tasks file for ots_deploy

- name: Import Deploy OVA - {{ ovf_path }}
  community.vmware.vmware_deploy_ovf:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ esx_cluster_name }}"
    datastore: "{{ datastore_name }}"
    name: "{{ deploy_name }}"
    ovf: '{{ ovf_path }}'
    networks:
      "ONTAP Select Deploy VM Network": "{{ mgt_network }}"
    properties:
      gateway: '{{ deploy_gateway }}'
      proxy_url: '{{ deploy_proxy_url }}'
      netMask: '{{ deploy_netMask }}'
      password: '{{ deploy_pwd }}'
      product_company: '{{ deploy_product_company }}'
      ipAddress: '{{ deploy_ipAddress }}'
      primaryDNS: '{{ deploy_primaryDNS }}'
      secondaryDNS: '{{ deploy_secondaryDNS }}'
      hostname: '{{ deploy_name }}'
      searchDomains: '{{ deploy_searchDomains }}'
    power_on: yes
    wait_for_ip_address: false
    allow_duplicates: no
  delegate_to: localhost

- name: wait for connectivity
  wait_for_connection:
    delay: 60
    timeout: 300  