---
- name: Install dependencies on RHEL 9
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Python 3.10.12 is installed
      yum:
        name: python3.10
        state: present

    - name: Configure pip to use internal repository
      copy:
        dest: /etc/pip.conf
        content: |
          [global]
          index-url = http://your-on-prem-repo/simple
          trusted-host = your-on-prem-repo

    - name: Upgrade pip to the latest version
      pip:
        name: pip
        state: latest
        executable: pip3.10

    - name: Install system dependencies
      yum:
        name:
          - cmake
          - make
          - gcc
          - gcc-c++
          - openssl-devel
          - python3-devel
        state: present

    - name: Install Python packages
      pip:
        name:
          - pyyaml
          - packaging
          - requests[security]
          - xmltodict
          - msgraph-sdk==1.0.0
        executable: pip3.10

    - name: Install Ansible
      pip:
        name: ansible==8.7.0
        executable: pip3.10

    - name: Install ONTAP Ansible Collection from Tar
      ansible.builtin.command:
        cmd: ansible-galaxy collection install /files/ontap-collection.tar.gz --offline
