# roles/prepare_vmware/tasks/main.yml
---
- name: Install pyvmomi
  pip:
    name: pyvmomi
    executable: pip3
  become: yes

- name: Create resource pool
  community.vmware.vmware_resource_pool:
    hostname: "{{ target_vcenter_or_esxi_host }}"
    username: "{{ host_login }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ esx_cluster_name }}"
    resource_pool: "ONTAP_Resource_Pool"
    state: present
  delegate_to: localhost

- name: Create VM folder
  community.vmware.vcenter_folder:
    hostname: "{{ target_vcenter_or_esxi_host }}"
    username: "{{ host_login }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "storage/VMs/ONTAP_VMs"
    state: present
  delegate_to: localhost
